trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: node-app

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'azure-service-conn'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'
    tags: |
      latest
