trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: node-app
  acrName: poc10acr.azurecr.io

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-service-conn'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name poc10acr

- script: |
    docker build -t $(acrName)/$(imageName):latest app/
  displayName: 'Build Docker Image'

- script: |
    docker push $(acrName)/$(imageName):latest
  displayName: 'Push Docker Image'
